### ISSUE TITLE
Installing Dependabot 

### ISSUE THREAD

**Issue by ArneTR** [green-coding-solutions/DBMS-bench#2]
Hey @dan-mm 

can you install Depenabot in this repo to auto update the compose.yml file please

**Comment by dan-mm** [comment]
So surprisingly dependabot doesn't currently support updating compose.yml files O.O

Thread on the issue [here](https://github.com/dependabot/dependabot-core/issues/390). its been a very requested feature since 2018. 

Not sure the best way to proceed here yet. Changing this repo to use dockerfiles seems a bit awkward as we reference the compose.yml files in the usage_scenario, so I think we need them as such. There's a proposed workaround [outlined here](https://github.com/dependabot/dependabot-core/issues/390#issuecomment-1062170379), but that also requires changing the compose.yml file in a way that I think will interfere with the imports.

**Comment by dan-mm** [comment]
There is also [Renovate](https://docs.renovatebot.com), which from a cursory glance seems like a more fully-featured version of dependabot... but I haven't taken too close a look at it yet.

**Comment by ArneTR** [comment]
we will do it manually for now then
